### ISSUE TITLE
PlantUML server not rendering diagrams

### ISSUE THREAD

**Issue by Kevin-Prichard** [sen-den/django-model2puml#9]
First of all thanks for developing this.  Second of all, this is not directly your problem, but please read on.

I inherited a Django app with about 70 models.  They all are linked in one giant network of foreign key relations, and it does what it's supposed to.

So I install django-model2puml and run it.  I generated a puml without `--add-help` or `--add-choices` and it was about 65k characters.

I upload it to plantuml.com which gets me a broken image icon in return.  I try a few things, no joy.

So I downloaded both versions of the Docker image (jetty and tomcat) and try them both.  Both failed.  But here I see that the web form ships the puml to the server in the URL as a base 64-encoded parameter.  The URL winds up being 18k or so characters.  The browser is fine with that, but both servers throw errors.

Any idea how to reconfigure either server to accept longer URIs?  I know I'm asking a Python dev about Java servers, but thought I'd try.  Thanks

**Comment by petterreinholdtsen** [comment]
Perhaps you should be better off by installing the plantuml Debian package using Debian, https://www.debian.org/, and generating the diagram locally without using a server?

**Comment by Kevin-Prichard** [comment]
Thank you for the suggestion, I will try that now.
